import matter from 'gray-matter'
import { Todo, StarRole, StarRoleGroup } from '../db'

export interface TodoWithRelations extends Todo {
	starRoleData?: StarRole
	starRoleGroupData?: StarRoleGroup
}

export function todoToMarkdown(todo: TodoWithRelations): string {
	return matter.stringify('', buildFrontMatterData(todo))
}

export function buildFrontMatterData(
	todo: TodoWithRelations,
): Record<string, unknown> {
	const data: Record<string, unknown> = {
		id: todo.id,
		title: todo.title,
	}

	if (todo.starPoints !== undefined) {
		data.starPoints = todo.starPoints
	}

	if (todo.starRoleData) {
		data.starRole = todo.starRoleData.title
		if (todo.starRoleGroupData) {
			data.starRoleGroup = todo.starRoleGroupData.title
		}
	}

	if (todo.completedAt) {
		data.completedAt = todo.completedAt
	}

	data.exportedAt = new Date()

	return data
}

export function updateFrontMatter(
	existingContent: string,
	todo: TodoWithRelations,
): string {
	const { content: body } = matter(existingContent)
	return matter.stringify(body, buildFrontMatterData(todo))
}

export function generateFilename(todo: Todo): string {
	const safeTitle = todo.title
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '')
		.slice(0, 50)

	const shortId = todo.id
		.replace(/[^a-z0-9]/gi, '')
		.toLowerCase()
		.slice(-8)

	return `${safeTitle}_${shortId}.md`
}

export function createManifest(
	todos: TodoWithRelations[],
	starRoles: StarRole[],
	starRoleGroups: StarRoleGroup[],
): string {
	const manifest = {
		exportedAt: new Date().toISOString(),
		version: '1.0.0',
		stats: {
			totalTodos: todos.length,
			activeTodos: todos.filter(t => !t.completedAt).length,
			completedTodos: todos.filter(t => t.completedAt).length,
			todosWithStarPoints: todos.filter(t => t.starPoints !== undefined).length,
			todosWithStarRoles: todos.filter(t => t.starRoleData).length,
		},
		starRoles: starRoles.map(sr => ({
			id: sr.id,
			title: sr.title,
			group: starRoleGroups.find(g => g.id === sr.starRoleGroupId)?.title,
		})),
		starRoleGroups: starRoleGroups.map(g => ({
			id: g.id,
			title: g.title,
		})),
	}

	const frontMatter = `---
type: manifest
exportedAt: ${manifest.exportedAt}
version: ${manifest.version}
---

`

	const content = `# Starfocus Export Manifest

## Statistics

| Metric | Count |
|--------|-------|
| Total Todos | ${manifest.stats.totalTodos} |
| Active Todos | ${manifest.stats.activeTodos} |
| Completed Todos | ${manifest.stats.completedTodos} |
| With Star Points | ${manifest.stats.todosWithStarPoints} |
| With Star Roles | ${manifest.stats.todosWithStarRoles} |

## Star Roles

${starRoles
	.map(sr => {
		const group = starRoleGroups.find(g => g.id === sr.starRoleGroupId)
		return `- **${sr.title}**${group ? ` (${group.title})` : ''}`
	})
	.join('\n')}

## Star Role Groups

${starRoleGroups.map(g => `- **${g.title}**`).join('\n')}

---

*This manifest was automatically generated by Starfocus.*
`

	return frontMatter + content
}
