import { Todo, StarRole, StarRoleGroup } from '../db'

export interface TodoWithRelations extends Todo {
	starRoleData?: StarRole
	starRoleGroupData?: StarRoleGroup
}

export function todoToMarkdown(todo: TodoWithRelations): string {
	const frontMatter = buildFrontMatter(todo)
	return `---\n${frontMatter}---`
}

function buildFrontMatter(todo: TodoWithRelations): string {
	const lines: string[] = []

	lines.push(`id: "${todo.id}"`)
	lines.push(`title: "${escapeYamlString(todo.title)}"`)

	if (todo.starPoints !== undefined) {
		lines.push(`starPoints: ${todo.starPoints}`)
	}

	if (todo.starRoleData) {
		lines.push(`starRole: "${escapeYamlString(todo.starRoleData.title)}"`)
		if (todo.starRoleGroupData) {
			lines.push(
				`starRoleGroup: "${escapeYamlString(todo.starRoleGroupData.title)}"`,
			)
		}
	}

	if (todo.completedAt) {
		lines.push(`completedAt: ${todo.completedAt.toISOString()}`)
	}

	lines.push(`exportedAt: ${new Date().toISOString()}`)

	return lines.join('\n') + '\n'
}

function escapeYamlString(str: string): string {
	return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

/**
 * Generates a safe filename from a todo title
 */
export function generateFilename(todo: Todo): string {
	// Create a safe filename from the title
	const safeTitle = todo.title
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '')
		.slice(0, 50)

	const shortId = todo.id
		.slice(-8)
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '')

	return `${safeTitle}-${shortId}.md`
}

/**
 * Creates a manifest file with metadata about the export
 */
export function createManifest(
	todos: TodoWithRelations[],
	starRoles: StarRole[],
	starRoleGroups: StarRoleGroup[],
): string {
	const manifest = {
		exportedAt: new Date().toISOString(),
		version: '1.0.0',
		stats: {
			totalTodos: todos.length,
			activeTodos: todos.filter(t => !t.completedAt).length,
			completedTodos: todos.filter(t => t.completedAt).length,
			todosWithStarPoints: todos.filter(t => t.starPoints !== undefined).length,
			todosWithStarRoles: todos.filter(t => t.starRoleData).length,
		},
		starRoles: starRoles.map(sr => ({
			id: sr.id,
			title: sr.title,
			group: starRoleGroups.find(g => g.id === sr.starRoleGroupId)?.title,
		})),
		starRoleGroups: starRoleGroups.map(g => ({
			id: g.id,
			title: g.title,
		})),
	}

	const frontMatter = `---
type: manifest
exportedAt: ${manifest.exportedAt}
version: ${manifest.version}
---

`

	const content = `# Starfocus Export Manifest

## Statistics

| Metric | Count |
|--------|-------|
| Total Todos | ${manifest.stats.totalTodos} |
| Active Todos | ${manifest.stats.activeTodos} |
| Completed Todos | ${manifest.stats.completedTodos} |
| With Star Points | ${manifest.stats.todosWithStarPoints} |
| With Star Roles | ${manifest.stats.todosWithStarRoles} |

## Star Roles

${starRoles
	.map(sr => {
		const group = starRoleGroups.find(g => g.id === sr.starRoleGroupId)
		return `- **${sr.title}**${group ? ` (${group.title})` : ''}`
	})
	.join('\n')}

## Star Role Groups

${starRoleGroups.map(g => `- **${g.title}**`).join('\n')}

---

*This manifest was automatically generated by Starfocus.*
`

	return frontMatter + content
}
