import matter from 'gray-matter'
import {
	Todo,
	StarRole,
	StarRoleGroup,
	AsteroidFieldOrder,
	WayfinderOrder,
} from '../db'

export interface TodoWithRelations extends Todo {
	starRoleData?: StarRole
	starRoleGroupData?: StarRoleGroup
}

export function todoToMarkdown(todo: TodoWithRelations): string {
	return matter.stringify('', buildFrontMatterData(todo))
}

export function buildFrontMatterData(
	todo: TodoWithRelations,
): Record<string, unknown> {
	const data: Record<string, unknown> = {
		id: todo.id,
		title: todo.title,
	}

	if (todo.starPoints !== undefined) {
		data.starPoints = todo.starPoints
	}

	if (todo.starRoleData) {
		data.starRole = todo.starRoleData.title
		if (todo.starRoleGroupData) {
			data.starRoleGroup = todo.starRoleGroupData.title
		}
	}

	if (todo.completedAt) {
		data.completedAt = todo.completedAt
	}

	data.exportedAt = new Date()

	return data
}

export function updateFrontMatter(
	existingContent: string,
	todo: TodoWithRelations,
): string {
	const { content: body } = matter(existingContent)
	return matter.stringify(body, buildFrontMatterData(todo))
}

export function generateFilename(todo: Todo): string {
	const safeTitle = todo.title
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-|-$/g, '')
		.slice(0, 50)

	const shortId = todo.id
		.replace(/[^a-z0-9]/gi, '')
		.toLowerCase()
		.slice(-8)

	return `${safeTitle}_${shortId}.md`
}

export function createManifest(
	todos: TodoWithRelations[],
	starRoles: StarRole[],
	starRoleGroups: StarRoleGroup[],
): string {
	const manifest = {
		exportedAt: new Date().toISOString(),
		version: '1.0.0',
		stats: {
			totalTodos: todos.length,
			activeTodos: todos.filter(t => !t.completedAt).length,
			completedTodos: todos.filter(t => t.completedAt).length,
			todosWithStarPoints: todos.filter(t => t.starPoints !== undefined).length,
			todosWithStarRoles: todos.filter(t => t.starRoleData).length,
		},
		starRoles: starRoles.map(sr => ({
			id: sr.id,
			title: sr.title,
			group: starRoleGroups.find(g => g.id === sr.starRoleGroupId)?.title,
		})),
		starRoleGroups: starRoleGroups.map(g => ({
			id: g.id,
			title: g.title,
		})),
	}

	const frontMatter = `---
type: manifest
exportedAt: ${manifest.exportedAt}
version: ${manifest.version}
---

`

	const content = `# Starfocus Export Manifest

## Statistics

| Metric | Count |
|--------|-------|
| Total Todos | ${manifest.stats.totalTodos} |
| Active Todos | ${manifest.stats.activeTodos} |
| Completed Todos | ${manifest.stats.completedTodos} |
| With Star Points | ${manifest.stats.todosWithStarPoints} |
| With Star Roles | ${manifest.stats.todosWithStarRoles} |

## Star Roles

${starRoles
	.map(sr => {
		const group = starRoleGroups.find(g => g.id === sr.starRoleGroupId)
		return `- **${sr.title}**${group ? ` (${group.title})` : ''}`
	})
	.join('\n')}

## Star Role Groups

${starRoleGroups.map(g => `- **${g.title}**`).join('\n')}

---

*This manifest was automatically generated by Starfocus.*
`

	return frontMatter + content
}

interface OrderEntry {
	todoId: string
	order: string
	snoozedUntil?: Date
}

function createOrderListMarkdown(
	title: string,
	orderEntries: OrderEntry[],
	todosById: Map<string, Todo>,
): string {
	const sorted = [...orderEntries].sort((a, b) =>
		a.order.localeCompare(b.order),
	)

	const items = sorted
		.map(entry => {
			const todo = todosById.get(entry.todoId)
			if (!todo) return null
			const filename = generateFilename(todo)
			const link = `[${todo.title}](${filename})`
			const snoozeNote = entry.snoozedUntil
				? ` *(snoozed until ${entry.snoozedUntil.toISOString().split('T')[0]})*`
				: ''
			return `${link}${snoozeNote}`
		})
		.filter((item): item is string => item !== null)

	const frontMatter = `---
type: order-list
exportedAt: ${new Date().toISOString()}
---

`

	const numberedList = items.map((item, i) => `${i + 1}. ${item}`).join('\n')
	return frontMatter + `# ${title}\n\n${numberedList}\n`
}

export function createAsteroidFieldFile(
	orderEntries: AsteroidFieldOrder[],
	todos: Todo[],
): string {
	const todosById = new Map(todos.map(t => [t.id, t]))
	return createOrderListMarkdown('Asteroid Field', orderEntries, todosById)
}

export function createWayfinderFile(
	orderEntries: WayfinderOrder[],
	todos: Todo[],
): string {
	const todosById = new Map(todos.map(t => [t.id, t]))
	return createOrderListMarkdown('Wayfinder', orderEntries, todosById)
}
